"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import documentreview as components_documentreview
from ...models.components import httpmetadata as components_httpmetadata
from athenacopilotsdk import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional


class ReviewModel(str, Enum):
    GPT_3_5_TURBO = 'gpt-3.5-turbo'
    CLAUDE_3_HAIKU = 'claude-3-haiku'


class FinalModel(str, Enum):
    GPT_3_5_TURBO = 'gpt-3.5-turbo'
    GPT_4 = 'gpt-4'
    CLAUDE_INSTANT_1 = 'claude-instant-1'
    CLAUDE_2 = 'claude-2'
    CLAUDE_3_HAIKU = 'claude-3-haiku'
    CLAUDE_3_SONNET = 'claude-3-sonnet'
    CLAUDE_3_OPUS = 'claude-3-opus'
    MIXTRAL = 'mixtral'
    MISTRAL_SMALL = 'mistral-small'
    MISTRAL_MEDIUM = 'mistral-medium'
    MISTRAL_LARGE = 'mistral-large'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateDocumentReviewRequestBody:
    message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    brain_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('brain_id'), 'exclude': lambda f: f is None }})
    document_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('document_id'), 'exclude': lambda f: f is None }})
    review_model: Optional[ReviewModel] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('review_model'), 'exclude': lambda f: f is None }})
    final_model: Optional[FinalModel] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('final_model'), 'exclude': lambda f: f is None }})
    active_reading_instructions: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('active_reading_instructions'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateDocumentReviewResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    document_review: Optional[components_documentreview.DocumentReview] = dataclasses.field(default=None)
    r"""Successful creation of document review"""
    

