"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from typing import Dict, List, Optional


@dataclasses.dataclass
class DeleteBrainBrainIDRequest:
    brain_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'brain_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class DeleteBrainBrainIDResponseBody:
    r"""OK"""
    



@dataclasses.dataclass
class DeleteBrainBrainIDResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    headers: Dict[str, List[str]] = dataclasses.field()
    object: Optional[DeleteBrainBrainIDResponseBody] = dataclasses.field(default=None)
    r"""OK"""
    

