"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from dataclasses_json import Undefined, dataclass_json
from typing import Dict, List, Optional


@dataclasses.dataclass
class File:
    file_name: str = dataclasses.field(metadata={'multipart_form': { 'field_name': 'file' }})
    content: bytes = dataclasses.field(metadata={'multipart_form': { 'content': True }})
    



@dataclasses.dataclass
class PostDocumentBrainIDFileRequestBody:
    file: Optional[File] = dataclasses.field(default=None, metadata={'multipart_form': { 'file': True }})
    



@dataclasses.dataclass
class PostDocumentBrainIDFileRequest:
    brain_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'brain_id', 'style': 'simple', 'explode': False }})
    request_body: Optional[PostDocumentBrainIDFileRequestBody] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'multipart/form-data' }})
    



@dataclasses.dataclass
class PostDocumentBrainIDFileResponseBody:
    r"""OK"""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PostDocumentBrainIDFileResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    headers: Dict[str, List[str]] = dataclasses.field()
    object: Optional[PostDocumentBrainIDFileResponseBody] = dataclasses.field(default=None)
    r"""OK"""
    

