"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from athenacopilotsdk import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Dict, List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PostChatListInteractionsRequestBody:
    chat_thread_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('chat_thread_id'), 'exclude': lambda f: f is None }})
    r"""Id of chat to which you want to send message"""
    text: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('text'), 'exclude': lambda f: f is None }})
    r"""message"""
    



@dataclasses.dataclass
class PostChatListInteractionsResponseBody:
    r"""OK"""
    



@dataclasses.dataclass
class PostChatListInteractionsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    headers: Dict[str, List[str]] = dataclasses.field()
    object: Optional[PostChatListInteractionsResponseBody] = dataclasses.field(default=None)
    r"""OK"""
    

