"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from typing import Dict, List, Optional


@dataclasses.dataclass
class PostChatbotResetRequest:
    chatbot_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'chatbot_id', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class PostChatbotResetResponseBody:
    r"""OK"""
    



@dataclasses.dataclass
class PostChatbotResetResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    headers: Dict[str, List[str]] = dataclasses.field()
    object: Optional[PostChatbotResetResponseBody] = dataclasses.field(default=None)
    r"""OK"""
    

